### ISSUE TITLE
App fails to start after upgrading to CUDA 13.x—missing cudart64_12.dll

### ISSUE THREAD

**Issue by Haseeb-1698** [hyperfield/ai-file-sorter#24]
After upgrading my system to CUDA Toolkit 13.x, running the AI File Sorter application fails with a "cudart64_12.dll not found" error. It appears the executable is hardcoded to search for cudart64_12.dll from CUDA 12.x, but this DLL is not included with CUDA 13.x.
Please consider updating the code to support CUDA 13.x runtimes, or make the CUDA DLL detection compatible with newer major versions (e.g., look for cudart64_13.dll if 12.x is not installed). This would allow users to run the app on modern environments without needing to downgrade or manually manage old dependencies. Thank you!

<img width="687" height="594" alt="Image" src="https://github.com/user-attachments/assets/f73265ef-b4fe-428f-82f9-a9552d45b7ab" />

**Comment by hyperfield** [comment]
Thanks for reporting this. It turns out that `llama-cpp` has a hard dependency on the version of `cudart64_xx.dll`. I'm going to include the necessary DLLs for CUDA 13 in the upcoming new version of the app.

**Comment by CarlosValenzuela1** [comment]
I had the same error, I was missing:

- cudart64_12.dll
- cublas64_12.dll
- cublaslt64_12.dll

I just downloaded the latest ones from dllme.com and put them in the lib folder (of this program) and now everything opened.

**Comment by hyperfield** [comment]
The app (version 0.9.3) now works with CUDA 13 on Windows. This means, however, that previous versions of CUDA are no longer supported due to how `llama.cpp` is compiled.
